### ISSUE TITLE
Crear pantalla principal

### ISSUE THREAD

**Issue by agustinruatta** [agustinruatta/flatron#15]
Como usuario del sistema quiero ver una pantalla principal para poder acceder a los diferentes módulos del software.

**Comment by agustinruatta** [comment]
Diseño de ejemplo:

![imagen](https://user-images.githubusercontent.com/11295335/45586125-c224e280-b8c7-11e8-8c70-081e6b2665f6.png)

**Comment by pepi014** [comment]
fondo 

![fondo](https://user-images.githubusercontent.com/40499206/45586561-8f7ee800-b8cf-11e8-9e31-e95e83ca9bc0.jpg)

**Comment by pepi014** [comment]
iconos

![cliente](https://user-images.githubusercontent.com/40499206/45586849-97408b80-b8d3-11e8-9cfd-2d63c92368e8.png)
![compra](https://user-images.githubusercontent.com/40499206/45586850-97408b80-b8d3-11e8-98be-3c756edd5768.png)
![informe](https://user-images.githubusercontent.com/40499206/45586851-97d92200-b8d3-11e8-90b7-e5501325c824.png)
![producto](https://user-images.githubusercontent.com/40499206/45586852-97d92200-b8d3-11e8-92bc-e5b7a46a7ec0.png)
![proveedores](https://user-images.githubusercontent.com/40499206/45586853-9871b880-b8d3-11e8-849c-238e8851e6cb.png)
![venta](https://user-images.githubusercontent.com/40499206/45586854-9871b880-b8d3-11e8-9531-224cac798354.png)

**Comment by pepi014** [comment]
![image](https://user-images.githubusercontent.com/40499206/46245197-4b581100-c3c0-11e8-9ec9-d87f2afec8d4.png)

**Comment by agustinruatta** [comment]
https://github.com/agustinruatta/flatron/pull/31 mergeado.

Cierro issue.
